### ISSUE TITLE
Metronome v3.13.5, released.

### ISSUE THREAD

**Issue by maranda** [YunoHost/metronome#15]
- It upgrades support for XEP-0215, External Services Discovery
- It introduces support for XEP-0278, Jingle Relay Nodes
- It brings basic security for the Telnet Console, by adding an optional password login
- Fixes routing for messages to bare jid, so that they won't break Jingle Session Initiations
- Adds logging facilities for XHTML-IM messages
- Some minor bug fixes

This update brings external services discovery support to facilitate Audio / Video conferencing in apps like Movim and Conversations, I strongly advise on its implementation.

**Comment by alexAubin** [comment]
Thank you for your work, I triggered a build on our infra (still in testing for now though, will release as stable with Yunohost 3.8)

Out of curiosity, is it also relevant for Jitsi ? I see that Yalh contributed to the changelog ;)

**Comment by maranda** [comment]
It could be relevant but that commit was needed to run some module ported from Prosody modules afair.

Jitsi *should* support Jingle Relay Nodes, but I'm my tests it seems to still to favor resolving STUN/TURN services using SRV lookups. But still might bring useful stuff for the upcoming times.

**Comment by alexAubin** [comment]
Alright, thanks !
