### ISSUE TITLE
Metronome v3.14.1 released

### ISSUE THREAD

**Issue by maranda** [YunoHost/metronome#18]
It just adds a change to cope with the wrong behaviour of Conversations that doesn't allow to configure rooms to enable MAM.

So a few options have been changed to allow to fully specify the default configuration of rooms on creations.

See: https://github.com/maranda/metronome/releases/tag/v3.14.1

**Comment by kay0u** [comment]
I'm closing this issue since it was already used in YunoHost 4.0, thank you for your work
