### ISSUE TITLE
Prosody Modules - Backwards Compatibility?

### ISSUE THREAD

**Issue by imattau** [YunoHost/metronome#19]
Do modules created for Prosody work with Metronome?

For example，I want to use RSS feeds automatically into a pubsub, and Prosody has a module for that - https://modules.prosody.im/mod_pubsub_feeds.html.

Could this module be dropped into Metronome, or does Metronome have an equivalent?

**Comment by maranda** [comment]
Some simple modules may work out the box without an issue, but after seven years both codebases almost completely diverge so anything beyond "simple" will require backporting

**Comment by maranda** [comment]
Also I suggest opening issues directly https://github.com/maranda/metronome
