### ISSUE TITLE
Consider updating to latest trunk revision (3.8.13)

### ISSUE THREAD

**Issue by maranda** [YunoHost/metronome#2]
It has several bug fixes and improvements and introduces support to:

XEP-277 SIFT filtering for remote entities and also message stanzas
XEP-344 Dialback without Dialback
XEP-363 HTTP Uploads
XEP-398 User Avatar to vCard-Based Avatar conversion

**Comment by alexAubin** [comment]
Hellow,

thank you for the notice !

At this point I think we don't plan on building any new metronome deb for jessie on our side (though we could, to be discussed) but we will probably when releasing stretch.

I was planning to wait for a 3.9 stable release before updating/merging, does this make any sense or is the version you suggest also stable ?

**Comment by maranda** [comment]
I overly tested 3.8.13 (upto https://github.com/maranda/metronome/commit/3a8596f9aeb68a1d5adbb4c9632ebbbc551dc72e) and it's very stable, also several leaks have been finally fixed.
For what regards 3.9, while I may release soon enough it may not be worth waiting for (3.8 isn't as stable as 3.8.13 ... regretedly). I also may change the release cycles to something different soon enough on a plus point as the model I currently use doesn't seem to be working at all anymore.

**Comment by alexAubin** [comment]
Alrighty, thanks for the info !

I'll take some time in the coming days to update and build for 3.8.13 / 3a8596f (for stretch).

Thanks !

**Comment by maranda** [comment]
Sorry I intended https://github.com/maranda/metronome/commit/b3aecbb23fa3de63cf74a0da466fd2a079dfe9c4 actually linked the wrong one 😆 (that's the latest commit, I linked the parent)

**Comment by alexAubin** [comment]
Alrighty, np :+1: :smile:

**Comment by maranda** [comment]
Updating issue to add latest minor release: https://github.com/maranda/metronome/releases/tag/v3.8.25

Fixes an important bug into mod_bosh.

Additions are:
- New registration API, improved IBR (with e-mail verification and account locking mechanism)
- Full Direct TLS support for S2S (and also c2s, see XEP-0368)
- Push Notifications (XEP-0357)
